package com.chieh.umdp.generic.entity;
// Generated 2018/2/8 ���� 04:37:16 by Hibernate Tools 5.2.8.Final

/**
 * CurSystemMsg generated by hbm2java
 */
public class CurSystemMsg implements java.io.Serializable {

	private Long msgId;
	private int msgCode;
	private String description;

	public CurSystemMsg() {
	}

	public CurSystemMsg(int msgCode, String description) {
		this.msgCode = msgCode;
		this.description = description;
	}

	public Long getMsgId() {
		return this.msgId;
	}

	public void setMsgId(Long msgId) {
		this.msgId = msgId;
	}

	public int getMsgCode() {
		return this.msgCode;
	}

	public void setMsgCode(int msgCode) {
		this.msgCode = msgCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
