package com.chieh.umdp.generic.entity;
// Generated 2018/2/8 ���� 04:37:16 by Hibernate Tools 5.2.8.Final

/**
 * CurUser generated by hbm2java
 */
public class CurUser implements java.io.Serializable {

	private long userId;
	private String account;
	private String password;
	private String userName;
	private int aothority;
	private String mail;

	public CurUser() {
	}

	public CurUser(long userId, String account, String password, String userName, int aothority) {
		this.userId = userId;
		this.account = account;
		this.password = password;
		this.userName = userName;
		this.aothority = aothority;
	}

	public CurUser(long userId, String account, String password, String userName, int aothority, String mail) {
		this.userId = userId;
		this.account = account;
		this.password = password;
		this.userName = userName;
		this.aothority = aothority;
		this.mail = mail;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getAothority() {
		return this.aothority;
	}

	public void setAothority(int aothority) {
		this.aothority = aothority;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
